# Generated by Django 4.0.2 on 2022-05-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationcategory',
            options={'ordering': ['-name'], 'verbose_name': 'Documentation', 'verbose_name_plural': 'Documentation'},
        ),
    ]
