# Generated by Django 4.0.2 on 2022-05-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0002_alter_documentationcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationcategory',
            options={'ordering': ['-name'], 'verbose_name': 'Documentation Category', 'verbose_name_plural': 'Documentation Categories'},
        ),
    ]
