# Generated by Django 4.0.2 on 2022-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0005_alter_bot_owner_alter_bot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
