# Generated by Django 4.0.2 on 2022-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0006_alter_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
