# Generated by Django 4.0.2 on 2022-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0007_alter_bot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='request_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=5),
        ),
        migrations.AddField(
            model_name='bot',
            name='required_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
