# Generated by Django 4.0.2 on 2022-05-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0008_bot_request_type_bot_required_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='required_authentication',
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payload_url', models.CharField(max_length=50)),
                ('event_type', models.CharField(blank=True, choices=[('on_vit_mention', 'on_vit_mention'), ('on_comment_mention', 'on_comment_mention'), ('on_follow', 'on_follow'), ('on_message', 'on_message')], max_length=50, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('required_authentication', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='develop.bot')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
