# Generated by Django 4.0.2 on 2022-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0009_remove_bot_endpoint_remove_bot_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.CharField(blank=True, choices=[('on_vit_mention', 'On Vit Mention'), ('on_comment_mention', 'On Comment Mention'), ('on_follow', 'On Follow'), ('on_message', 'On Message')], max_length=50, null=True),
        ),
    ]
