# Generated by Django 4.0.2 on 2022-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0010_alter_webhook_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded')], default='application/json', max_length=50),
        ),
    ]
