# Generated by Django 4.0.2 on 2022-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_nsfw',
            field=models.BooleanField(default=False, help_text='Allow NSFW content to be displayed', verbose_name='Allow NSFW'),
        ),
    ]
