# Generated by Django 4.0.1 on 2022-01-27 11:07

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/uploads/default.jpg', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/', verbose_name='Profile Image'),
        ),
    ]
