# Generated by Django 3.2.10 on 2021-12-29 14:53

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/uploads/default.jpg', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/'),
        ),
    ]
