# Generated by Django 3.2.9 on 2021-12-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/img/default.jpg', upload_to='uploads/'),
        ),
    ]
