# Generated by Django 3.2.9 on 2021-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notif',
            field=models.BooleanField(default=True, help_text='Get Email Notifications'),
        ),
    ]
