# Generated by Django 3.2.10 on 2022-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
