# Generated by Django 4.0.2 on 2022-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_allow_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allow_nsfw',
            field=models.BooleanField(default=False, verbose_name='Allow NSFW Content'),
        ),
    ]
