# Generated by Django 4.0.1 on 2022-01-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_badge'),
        ('accounts', '0002_profile_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(to='core.Badge'),
        ),
    ]
