# Generated by Django 3.2.9 on 2021-12-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_notif',
            field=models.BooleanField(default=True, verbose_name='Get Email Notifications'),
        ),
    ]
