# Generated by Django 4.0.2 on 2022-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_allow_nsfw'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('colorful', 'Colorful')], default='online', max_length=50),
        ),
    ]
