# Generated by Django 3.2.9 on 2021-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/img/default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
