# Generated by Django 4.0.2 on 2022-11-12 14:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='/uploads/default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='uploads/', verbose_name='Profile Image'),
        ),
    ]
