# Generated by Django 4.2.1 on 2023-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Tell us about yourself",
                max_length=500,
                null=True,
                verbose_name="About Yourself",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="It help to know when is your birthday", null=True
            ),
        ),
    ]
