# Generated by Django 4.2.1 on 2023-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_bio_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dark_mode",
            field=models.BooleanField(
                default=False, help_text="Enable dark mode", verbose_name="Dark Mode"
            ),
        ),
    ]
