# Generated by Django 4.2.1 on 2023-06-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_dark_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="auth_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="dark_mode",
        ),
    ]
