# Generated by Django 4.0.2 on 2023-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_auth_token_remove_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
