# Generated by Django 4.0.2 on 2023-11-06 12:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 400], upload_to='uploads/'),
        ),
    ]
