# Generated by Django 4.2.7 on 2023-11-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rename_image_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="use_gravatar",
            field=models.BooleanField(default=True),
        ),
    ]
