# Generated by Django 4.2.7 on 2023-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_profile_use_gravatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="use_gravatar",
            field=models.BooleanField(default=False),
        ),
    ]
