# Generated by Django 4.0.2 on 2022-11-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='f4K7ML3V790cFBxdkhIe9g', max_length=255, unique=True)),
                ('DevProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='developer.devprofile')),
            ],
        ),
    ]
