# Generated by Django 4.0.2 on 2023-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Tell us about yourself', null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded')], default='application/json', help_text='The content type to use when sending the payload', max_length=50),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.CharField(blank=True, choices=[('on_vit_mention', 'On Vit Mention'), ('on_comment_mention', 'On Comment Mention'), ('on_follow', 'On Follow'), ('on_message', 'On Message')], help_text='The event type to listen for', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', help_text='The HTTP method to use when sending the payload', max_length=5),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(help_text='Unique name for the webhook', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='payload_url',
            field=models.CharField(help_text='The URL to send the payload to', max_length=50),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='required_authentication',
            field=models.BooleanField(default=False, help_text='Check this if you want to authenticate the webhook'),
        ),
    ]
