# Generated by Django 4.0.2 on 2022-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
