# Generated by Django 4.0.2 on 2022-11-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_rename_devprofile_token_devprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='devProfile',
            new_name='devprofile',
        ),
    ]
