# Generated by Django 4.0.2 on 2022-11-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_bot_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
