# Generated by Django 4.2.7 on 2024-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
