# Generated by Django 4.0.2 on 2022-10-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirments',
        ),
    ]
