# Generated by Django 4.2.1 on 2023-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "image"),
                            ("VIDEO", "video"),
                            ("AUDIO", "audio"),
                            ("OTHER", "other"),
                        ],
                        default="IMAGE",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
            ],
        ),
    ]
