# Generated by Django 4.0.1 on 2022-01-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_badge_color_alter_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(choices=[('success', 'Green'), ('info', 'Blue'), ('link', 'Purple'), ('primary', 'Turquoise'), ('warning', 'Yellow'), ('danger', 'Red'), ('dark', 'Black'), ('white', 'White')], max_length=50),
        ),
    ]
