# Generated by Django 4.0.1 on 2022-01-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_badge_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
