# Generated by Django 4.0.1 on 2022-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
