# Generated by Django 3.2.9 on 2021-12-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_email_notif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sdesc', models.CharField(max_length=255, verbose_name='Short Description')),
                ('body', models.TextField(verbose_name='Body')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='blog/imgs')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
