# Generated by Django 3.2.10 on 2021-12-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('comment', 'Comment'), ('like', 'Like'), ('follow', 'Follow'), ('abuse', 'Abuse')], max_length=20),
        ),
    ]
