# Generated by Django 3.2 on 2022-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('comment', 'Comment'), ('message', 'Message'), ('like', 'Like'), ('follow', 'Follow'), ('abuse', 'Abuse'), ('invitation', 'Invitation')], max_length=20),
        ),
    ]
