# Generated by Django 3.2.9 on 2021-12-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plustag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, help_text='You can upload upto one image per Vit', null=True, upload_to='uploads/images/')),
                ('video', models.FileField(blank=True, help_text='You can upload upto one video per Vit', null=True, upload_to='uploads/videos/')),
                ('like_count', models.IntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='liked_vits', to=settings.AUTH_USER_MODEL)),
                ('plustag', models.ManyToManyField(blank=True, to='vit.Plustag')),
                ('to_reply_users', models.ManyToManyField(related_name='to_reply_users', to=settings.AUTH_USER_MODEL)),
                ('to_reply_vits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vit.vit', verbose_name='To Reply Vit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
