# Generated by Django 4.0.2 on 2022-03-02 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plustag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Vit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, help_text='You can upload upto one image per Vit', null=True, upload_to='uploads/images/')),
                ('video', models.FileField(blank=True, help_text='You can upload upto one video per Vit', null=True, upload_to='uploads/videos/')),
                ('like_count', models.IntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='liked_vits', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(related_name='mentioned_vits', to=settings.AUTH_USER_MODEL)),
                ('plustag', models.ManyToManyField(blank=True, to='vit.Plustag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.vit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
