# Generated by Django 3.2.9 on 2021-12-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vit',
            name='to_reply_users',
        ),
        migrations.AlterField(
            model_name='vit',
            name='to_reply_vits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='vit.vit', verbose_name='To Reply Vit'),
        ),
    ]
