# Generated by Django 4.0.2 on 2022-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vit',
            name='nsfw',
            field=models.BooleanField(default=False, help_text='Mark as NSFW if the content is not safe for work', verbose_name='Is the Content NSFW?'),
        ),
    ]
