# Generated by Django 3.2.10 on 2022-01-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
