# Generated by Django 3.2.10 on 2021-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0002_auto_20211228_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='plustag',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
