# Generated by Django 3.2.10 on 2021-12-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0003_plustag_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plustag',
            options={'ordering': ['rating']},
        ),
    ]
