# Generated by Django 4.0.2 on 2022-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0003_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='embed_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('twitch', 'Twitch'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vine', 'Vine'), ('vitary', 'Vitary'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
