# Generated by Django 3.2.10 on 2021-12-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0004_alter_plustag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plustag',
            options={'ordering': ['-rating']},
        ),
    ]
