# Generated by Django 4.0.2 on 2022-05-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0004_embed_embed_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embed',
            name='embed_type',
        ),
    ]
