# Generated by Django 3.2.10 on 2021-12-29 14:53

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0005_alter_plustag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vit',
            name='image',
            field=models.ImageField(blank=True, help_text='You can upload upto one image per Vit', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='vit',
            name='video',
            field=models.FileField(blank=True, help_text='You can upload upto one video per Vit', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/videos/'),
        ),
    ]
