# Generated by Django 4.2.1 on 2023-06-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vit", "0008_alter_comment_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="vit",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="vit.vit",
            ),
        ),
        migrations.AlterField(
            model_name="vit",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="You can upload upto one image per vit",
                null=True,
                upload_to="uploads/images/",
            ),
        ),
        migrations.AlterField(
            model_name="vit",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="You can upload upto one video per vit",
                null=True,
                upload_to="uploads/videos/",
            ),
        ),
    ]
