# Generated by Django 4.2.1 on 2023-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vit", "0010_remove_vit_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="vit",
            name="contain_embed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vit",
            name="saved_embed",
            field=models.BooleanField(default=False),
        ),
    ]
