# Generated by Django 4.0.2 on 2023-07-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0011_vit_contain_embed_vit_saved_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='vit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='vit.vit'),
        ),
    ]
