# Generated by Django 4.0.2 on 2023-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0012_alter_embed_vit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vit',
            name='mdbody',
            field=models.TextField(blank=True, null=True),
        ),
    ]
