# Generated by Django 4.0.2 on 2023-08-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0013_vit_mdbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vit',
            name='contain_embed',
        ),
        migrations.RemoveField(
            model_name='vit',
            name='mdbody',
        ),
        migrations.RemoveField(
            model_name='vit',
            name='saved_embed',
        ),
    ]
