# Generated by Django 4.0.2 on 2023-11-06 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vit', '0014_remove_vit_contain_embed_remove_vit_mdbody_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_vits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vit',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_vits', to=settings.AUTH_USER_MODEL),
        ),
    ]
