# Generated by Django 4.2.7 on 2023-11-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="avatar",
            new_name="avatar_image",
        ),
    ]
