# Generated by Django 4.2.7 on 2023-11-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_avatar_userprofile_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
    ]
