# Generated by Django 3.2.9 on 2021-12-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='update_date',
        ),
    ]
